version: '3'

services:
  go:
    build:
      context: ./
      dockerfile: /docker/go/Dockerfile
    ports:
      - "8080:8080"

  django:
    build:
      context: ./
      dockerfile: /docker/python/Dockerfile
    ports:
      - "8000:8000"
